data:
  raw_data_uri: "raw_data.tar"
  local_path: "data"
  img_dir: "images_raw"
  annot_dir: "annotations_raw"
  img_db_uri: "img_db.csv"
  checkpoint_dir : "model_chkpts"
  app_dir: "app"

log:
  log_dir: "logs"

models:
  classes: ["Leonberg", "basenji", "malamute", "papillon", "chow", "dhole", "dingo", "Cardigan", "Brabancon_griffon", "boxer"]

app_data:
  local_path: "app_data"
  model: "yolov8_m_best.pt"
  breeds: ["Leonberg", "basenji", "malamute", "papillon", "chow", "dhole", "dingo", "Cardigan", "Brabancon_griffon", "boxer"]
  confidence: 0.1
  max_detections: 6